source 'https://supermarket.chef.io'

%w{bare-metal block-storage common compute
   dashboard database data-processing identity image
   integration-test network object-storage ops-database
   ops-messaging orchestration telemetry}.each do |cookbook|
      cookbook "openstack-#{cookbook}", github: "stackforge/cookbook-openstack-#{cookbook}", branch: 'master'
end
cookbook "openstack_client", github: "stackforge/cookbook-openstack-client", branch: 'master'

cookbook 'apache2'
cookbook 'apt'
cookbook 'aws'
cookbook 'build-essential'
cookbook 'ceph'
cookbook 'database'
cookbook 'erlang'
cookbook 'memcached'
cookbook 'mysql'
cookbook 'mysql2_chef_gem'
cookbook 'openssl'
cookbook 'postgresql'
cookbook 'python'
cookbook 'rabbitmq'
cookbook 'xfs'
cookbook 'yum'
cookbook 'selinux'
cookbook 'yum-epel'
cookbook 'statsd', github: 'att-cloud/cookbook-statsd'
