source "https://supermarket.chef.io"

cookbook 'apache2'
cookbook 'apt'
cookbook 'aws'
cookbook 'build-essential'
cookbook 'ceph'
cookbook 'database'
cookbook 'erlang'
cookbook 'memcached'
cookbook 'mysql'
cookbook 'mysql2_chef_gem'
cookbook 'openssl'
cookbook 'postgresql'
cookbook 'python'
cookbook 'rabbitmq'
cookbook 'xfs'
cookbook 'yum'
cookbook 'selinux'
cookbook 'yum-epel'
cookbook 'resource-control'
cookbook 'statsd', github: 'att-cloud/cookbook-statsd'

cookbook 'openstack-bare-metal', github: 'stackforge/cookbook-openstack-bare-metal', branch: "master"
cookbook 'openstack-block-storage', github: 'stackforge/cookbook-openstack-block-storage', branch: "master"
cookbook 'openstack-client', github: 'stackforge/cookbook-openstack-client', branch: "master"
#cookbook 'openstack-common', github: 'stackforge/cookbook-openstack-common', branch: "master"
cookbook 'openstack-common', path: "/home/andesm/git/openstack-chef-repo/berks-cookbooks/openstack-common"
cookbook 'openstack-compute', github: 'stackforge/cookbook-openstack-compute', branch: "master"
cookbook 'openstack-dashboard', github: 'stackforge/cookbook-openstack-dashboard', branch: "master"
cookbook 'openstack-database', github: 'stackforge/cookbook-openstack-database', branch: "master"
cookbook 'openstack-data-processing', github: 'stackforge/cookbook-openstack-data-processing', branch: "master"
cookbook 'openstack-identity', github: 'stackforge/cookbook-openstack-identity', branch: "master"
cookbook 'openstack-image', github: 'stackforge/cookbook-openstack-image', branch: "master"
cookbook 'openstack-integration-test', github: 'stackforge/cookbook-openstack-integration-test', branch: "master"
cookbook 'openstack-network', github: 'stackforge/cookbook-openstack-network', branch: "master"
cookbook 'openstack-object-storage', github: 'stackforge/cookbook-openstack-object-storage', branch: "master"
cookbook 'openstack-ops-database', github: 'stackforge/cookbook-openstack-ops-database', branch: "master"
cookbook 'openstack-ops-messaging', github: 'stackforge/cookbook-openstack-ops-messaging', branch: "master"
cookbook 'openstack-orchestration', github: 'stackforge/cookbook-openstack-orchestration', branch: "master"
cookbook 'openstack-telemetry', github: 'stackforge/cookbook-openstack-telemetry', branch: "master"
